language: ruby
rvm:
  - 2.1.2
addons:
  postgresql: '9.3'
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - psql -c 'create database travis_ci_test' -U postgres
  - npm install bower karma karma-jasmine karma-phantomjs-launcher
  - bower install
script:
  - node_modules/karma/bin/karma start --single-run
  - bundle exec rspec